language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - npm start validate
after_success:
  - npm install codecov
  - codecov
branches:
  only:
    - master
