language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - packages/**/node_modules
notifications:
  email: false
node_js:
  - '6'
install:
  - npm run bootstrap
script:
  - npm run validate
after_success:
  - npm install codecov
  - codecov
branches:
  only:
    - master
