dist: trusty
language: csharp
cache:
  directories:
    - node_modules
    - packages/**/node_modules
notifications:
  email: false
mono: none
dotnet: 1.1.0
before_install:
  - nvm install "$(jq -r '.engines.node' package.json)"
  - nvm use "$(jq -r '.engines.node' package.json)"
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
install:
  - npm install
  - npm run bootstrap
script:
  - npm run validate
after_success:
  - npm install codecov
  - codecov
branches:
  only:
    - master
